//подключаемые ресурсы
/resources:%gal_exe%C_StatLine.res;
/resources:%gal_exe%extfun.res;

/resources:%gal_exe%F_OSRep.res;
/resources:%gal_exe%L_PrnSopr.res;

/resources:%gal_exe%M_Up.res;

/resources:%gal_exe%L_Dover.res


/resources:%gal_exe%Z_katpodr.res

/resources:%gal_exe%F_BuhRep.res;
/resources:%gal_exe%F_NalogReg.res;

/resources:%gal_exe%L_SoprDoc.res;

/resources:%gal_exe%L_Sf.res;


/resources:%gal_exe%F_os.res;

/resources:%gal_exe%F_plpor.res;

/resources:%gal_exe%F_OSInvCard.res;

/resources:%gal_exe%F_OSoper.res;

/resources:%gal_exe%L_BaseDoc.res;
/resources:%gal_exe%L_sklad.res;
/resources:%gal_exe%L_ttndoc.res;

