  // Строковые константы - наименования иерархий
  CRMHierOrg        = 'Организации';
  CRMHierClient     = 'Клиенты';
  CRMHierDiler      = 'Дилеры';
  CRMHierConcur     = 'Конкуренты';
  CRMHierAdver      = 'Рекламопроизводители';
  CRMHierPartner    = 'Партнеры';
  CRMHierManager    = 'Менеджеры';
  CRMHierGood       = 'Товары и услуги';
  CRMHierGroup      = 'Группа товара или услуги';
  CRMHierType       = 'Тип товара или услуги';
  CRMHierPayForm    = 'Форма оплаты';
  CRMHierPayWay     = 'Способ оплаты';
  CRMHierDirect     = 'Направление реализации';
  CRMHierAdvAction  = 'Рекламные акции';
  CRMHierCity       = 'Населенный пункт';
  CRMHierEdIzm      = 'Единицы измерения';
  CRMHierAdverVid   = 'Вид рекламы';
  CRMHierAdverDir   = 'Направление рекламы';
  CRMHierContMethod = 'Метод контакта';

  // Максимальное число записей для демо-режима
  MaxRecInKatalog = 100;    // для каталогов
  MaxRecDocuments = 200;    // для документов

  coMinDBF        = 63001;  // Номера для подключаемыз dbf-файлов

  NameDefaultBarg = 'Остальные продажи';  // Наименование общей(собирательной) сделки,
                                          // в которую попадают продажи,
                                          // которые не привязаны ни к одной сделке
  // Значения поля Config.WhatType - тип конфигурации
  cnfCurrentGO = 1;  // Текущая конфигурация, гарантийное обслуживание
  cnfCurrentAO = 2;  // Текущая конфигурация, абонентское обслуживание
  cnfPredGO    = 11; // Предыдущая конфигурация, гарантийное обслуживание
  cnfPredAO    = 12; // Предыдущая конфигурация, абонентское обслуживание
   
