/*
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ                     (c) 1994,98 ชฎเฏฎเ ๆจ๏ €€’€                      บ
 บ เฎฅชโ        : €€’€                                                 บ
 บ ‘จแโฅฌ        : ฎคใซ์ “ฏเ ขซฅญจฅ เฅฌฎญโ ฌจ                               บ
 บ ฅเแจ๏        : 5.80                                                      บ
 บ  งญ ็ฅญจฅ    : ฎญแโ ญโ๋ ฌฎคใซ๏ “ฏเ ขซฅญจฅ เฅฌฎญโ ฌจ (กฅง hc-ชฎญแโ ญโ)   บ
 บ โขฅโแโขฅญญ๋ฉ : ใเฃ เคโ €ซฅชแ ญคเ                                        บ
 บ งฌฅญฅญจ๏     :                                                           บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/
Const

    cmRemGrafRem     = 65010;
    cmRemGrafRemA    = 65011;
    cmRemImpAkt      = 65012;
    cmRemMetod1      = 65013;
    cmRemMetod2      = 65014;
    cmRemMetod3      = 65015;
    cmRemMolObjRem   = 65016;
    cmRemNASTR       = 65017;
    cmRemNewAkt      = 65018;
    cmRemNormRem     = 65019;
    cmRemOpisObjRem  = 65020;
    cmRemAObjRem     = 65021;
    cmRemObjRem      = 65022;
    cmEnter          = 65023;
    cmRemMetod4      = 65024;
    cmRemPickObjRem1 = 65025;
    cmRemPickKatOrg1 = 65026;
    cmRemPickKatPodr1= 65027;
    cmRemPickKatMc1  = 65028;
    cmRemPickKatUsl1 = 65029;
    cmRemNewDescr1   = 65030;
    cmRemPickObjRem2 = 65031;
    cmRemPickKatOrg2 = 65032;
    cmRemPickKatPodr2= 65033;
    cmRemPickKatMc2  = 65034;
    cmRemPickKatUsl2 = 65035;
    cmRemNewDescr2   = 65036;
    cmRemPickTipObj1 = 65037;
    cmRemPickGrObj1  = 65038;
    cmRemPickKatMark1= 65039;
    cmRemPickKatTexN1= 65040;
    cmRemPickTipObj2 = 65041;
    cmRemPickGrObj2  = 65042;
    cmRemPickKatMark2= 65043;
    cmRemPickKatTexN2= 65044;
    cmRemGenTreeObj1 = 65049;
    cmRemGenTreeObj2 = 65050;
    cmRemGenTreeObj3 = 65051;
    cmRemGenTreeObj4 = 65052;
    cmRemGenTreeObj5 = 65053;
    cmRemGenTreeObj6 = 65054;
    cmRemTreeCloseAll= 65055;
    cmRemNewObjRem1  = 65056;
    cmRemNewObjRem2  = 65057;
    cmRemMove        = 65058;
    cmRemPickKurRem1 = 65059;
    cmRemPickIspRem1 = 65060;
    cmRemPickSposRem1= 65061;
    cmRemPickKurRem2 = 65062;
    cmRemPickIspRem2 = 65063;
    cmRemPickSposRem2= 65064;
    cmRemJourObj     = 65065;
    cmRemJourDef     = 65066;
    cmRemPickVidObj1 = 65067;
    cmRemPickFPCO1   = 65068;
    cmRemPickSpKau1  = 65069;
    cmRemPickIspOS1  = 65070;
    cmRemPickVidObj2 = 65071;
    cmRemPickFPCO2   = 65072;
    cmRemPickSpKau2  = 65073;
    cmRemPickIspOS2  = 65074;
    cmRemMetod5      = 65075;
    cmRemMetod6      = 65076;
    cmRemMetod0      = 65077;
    cmRemMetod7      = 65078;
