 const
   constTypeCatFactor = 30201;   //код записей значений факторов для хранения в таблице DISTDOCHIERARCHY
   constTypeNabor     = 30202;   //код записей значений набора соответствий для хранения в таблице DISTDOCHIERARCHY
   constFactorPers    = 30203;   //код записей значений Факторов сотрудника для хранения в таблице DISTDOCHIERARCHY
   constVidGraf       = 30204;   //код записей графиков  (список графиков)
   constRecPers       = 30205;   //код записей средней панели (сотрудники)
   constRecFact       = 30206;   //код записей нижней  панели(факторы)
   constTypeCatBound  = 30207;   //код записей значений ограничений профпригодности для хранения в таблице DISTDOCHIERARCHY
 end
